create database mrinal;
use mrinal;
CREATE TABLE SportsClub (
    id INT PRIMARY KEY,
    name VARCHAR(100),
    location VARCHAR(100),
    sport VARCHAR(50),
    founded_year INT,
    coach VARCHAR(100),
    captain VARCHAR(100),
    stadium VARCHAR(100),
    website VARCHAR(200),
    contact_email VARCHAR(100)
);
desc SportsClub;
CREATE TABLE HOTEL(
ID INTEGER(10),
ROOM_NUMBER VARCHAR(20),
ROOM_TYPE VARCHAR(20),
PRICE BIGINT(20),
HOTEL_NAME VARCHAR(20),
PLACE VARCHAR(20),
HOTEL_OWNER VARCHAR(20),
HOTEL_STATE VARCHAR(20),
HOYEL_PHONE BIGINT(20),
HOTEL_CITY VARCHAR(20)
);
desc HOTEL;
CREATE TABLE CARRENT(
ID INTEGER(10),
BRAND VARCHAR(20),
MODEL VARCHAR(20),
RENTAL_PRICE BIGINT(20),
CAR_COLOR VARCHAR(20),
CAR_AVAILABLE VARCHAR(20),
CAR_LOCATION VARCHAR(20),
CAR_YEAR INTEGER(20),
CUSTOMER_NAME VARCHAR(20),
CUSTOMER_PHONE BIGINT(20));
desc CARRENT;
CREATE TABLE ACCOUNTS(
ID INT(20),
ACCOUNT_NUMBER BIGINT(20),
ACCOUNT_HOLDER VARCHAR(20),
BALANCE BIGINT(20),
ACCOUNT_TYPE VARCHAR(20),
BRANCH VARCHAR(20),
IFSC_CODE VARCHAR(20),
ACCOUNT_OPEN_DATE DATE,
AMOUNT_DEPOSIT BIGINT(20),
AMOUNT_WITHDRAWN BIGINT(20));
desc ACCOUNTS;
CREATE TABLE GAMES(
ID INT(10),
GAME_NAME VARCHAR(20),
CATEGORY VARCHAR(20),
PLATFORM VARCHAR(20),
DEVELOPER VARCHAR(20),
PRICE INT(20),
RELEASE_DATE DATE,
PUBLISHER VARCHAR(20),
RATING INT(10),
GAME_LANGUAGE VARCHAR(20));
desc GAMES;
CREATE TABLE ARTISTS (
ID INT(10),
ARTIST_NAME VARCHAR(20),
ARTIST_GENRE VARCHAR(20),
ARTIST_COUNTRY VARCHAR(20),
ARTIST_YEAR_ESTABLISHED DATE,
ARTIST_WEBSITE VARCHAR(20),
PH_NO BIGINT(20),
E_MAIL VARCHAR(20),
ARTIST_GENDER VARCHAR(10),
DOB DATE);
desc ARTISTS;
CREATE TABLE Statues (
    id INT PRIMARY KEY,
    statue_name VARCHAR(100),
    artist_name VARCHAR(100),
    material VARCHAR(50),
    height VARCHAR(20),
    location VARCHAR(200),
    year_created INT,
    style VARCHAR(100),
    description VARCHAR(500),
    image_url VARCHAR(200)
);
CREATE TABLE Shoes (
    id INT PRIMARY KEY,
    brand VARCHAR(100),
    model VARCHAR(100),
    color VARCHAR(50),
    size VARCHAR(20),
    style VARCHAR(100),
    material VARCHAR(100),
    gender VARCHAR(20),
    price DECIMAL(10, 2),
    description VARCHAR(500)
);
CREATE TABLE Mobiles (
    id INT PRIMARY KEY,
    brand VARCHAR(100),
    model VARCHAR(100),
    color VARCHAR(50),
    storage_capacity VARCHAR(20),
    display_size VARCHAR(20),
    operating_system VARCHAR(50),
    price DECIMAL(10, 2),
    description VARCHAR(500),
    image_url VARCHAR(200)
);
CREATE TABLE Perfumes (
    id INT PRIMARY KEY,
    brand VARCHAR(100),
    name VARCHAR(100),
    fragrance_family VARCHAR(50),
    gender VARCHAR(20),
    volume VARCHAR(20),
    price DECIMAL(10, 2),
    description VARCHAR(500),
    image_url VARCHAR(200),
    color varchar(20)
);
